{% set pkgname = "bc" %}
{% set version = "1.06" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: http://ftpmirror.gnu.org/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: 4ef6d9f17c3c0d92d8798e35666175ecd3d8efac4009d6457b5c99cea72c0e33
  patches:
    - verify_checklib_results.sh.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - flex
  run:
    - flex

test:
  commands:
    - bc --version

about:
  home: https://www.gnu.org/software/bc/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: bc is an arbitrary precision numeric processing language.

extra:
  recipe-maintainers:
    - shahin
