{% set name = "bc" %}
{% set version = "1.07.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://ftpmirror.gnu.org/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62adfca89b0a1c0164c2cdca59ca210c1d44c3ffc46daf9931cf4942664cb02a
  patches:
    - verify_checklib_results.sh.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - bison
    - make
    - texinfo
  host:
    - flex

test:
  commands:
    - echo '1 > 2' | bc -l

about:
  home: "https://www.gnu.org/software/bc/"
  doc_url: "https://www.gnu.org/software/bc/manual/bc.html"
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: bc is an arbitrary precision numeric processing language.

extra:
  recipe-maintainers:
    - shahin
    - duncanmmacleod
    - jaimergp
