appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: VCkNvbaeep041xSGiJYcqtcpHv9D3/h6caLkQUUky3E2LhlhIVk4VquOUpUU0xRh64QalcZPdEdpWTCyM8QhLBaOCkO/HPp357BbMaA2fn+sPFlxQXrWATCSCy9xr6zDKXGl7ECNJDo7QJ3YB7vc8BKKuaV9mLhj7s9IGDsEugcBQeraSm0IeE1brTUFuWcKyBpnA6BaUE0A0/imfDRn3uVRwQTStdz19bYfmmVhaE895ee9sJYwy0PiOWmgtPkhzC9XzITZkiWKT1OEMp0p47x0fbFMPcXB7T9fLwEwQsM34siMuI8mH87rQvrjaP3kJlcGOATK4+XtxBNmnkEI1PGqiSY/UsrZ++m4cMK1CzM5jsSW4wuknp2HbuQwkLql4alTooYROKxtXSkg5Wiln6sS2GwwwYMRvlsLhJ6DUJtOWthzY7uqKzOh8xJ0snwrGhgeSd1ivTmjX7o+2dNh509RwKhPlqlu5SIH33NKwQjZZTvb6JkbwnHyMEcaaOyRSlDWCBOsIR3Jj7WAGP4aB1JPW4lIIt9zuC3GBrMWDD0TDSL5XvcRxDNakcEiAmpuXSSkjmjecv3ouP72tRWkXSNAxuhn5fbEgbO/3NAU2wxX2YTxmWJnwo1PfnKTmVMv4zBPhWUMIJ1RWeFGQO/mkB+ivbvS91yrPRfJ5Nk/fhE=}
