travis:
  secure:
    BINSTAR_TOKEN: aJH6CWiWIBnqChDmFXsuJlbX0yCSEUtlFdMerzoF6t+bDFHNJjO56jrz0P8b2zjM9YSVxVl1QOxpv1Ujq2LaFNCp9ltEBHWuUHtnWViMHMYxYIDn2zSr2QpXWf70xdqXcsT6e19jl43Vl5ZGXM+tB92BAL6hGuLlWUIHKlEzmqy60JPwODbjD242DNiBsqAxuZK/aahpy+768ly6RM1IR6Uzj/SMPej6m69vFqooyqnkszoaZX/TexJE1Dex0cPqBqW/dsQODDfQdBM3p6dyaKUbjMHFj8TFmAeKZ1+GI5RQyQ4QagtE6Fi5IwJPulXOsNUAk1fO7jLYF22+Nd8HSAfOpUVM0VX6XxlvMryDoIn6k5tE1pMlP7v9qQUhrQvbwa4amAfAbDAfYrZd7JprtZV02kozyE5TAzL5GoOujYZJzZ0DN1Toz8gJ/kmwDId4ClhUhF5e9GuTDs4VPQNs0TZvtSmG84eapwljXsCS6df7XTikgeHheshzdcpKCfop4WqQcUdCta1FvvGFL7HWN/kSU3gCa99YsBmG88Oma70tv17kksawLdR1y1nR4hBH6AO75Js6tfLBrUDjjlsreJIqw0i71+RyXs9Tgg/q5GnAtICPrv3/U+gvxjPz8QPcVRi8+0rk45Mt2xZUBOtA2gOZgLxLvaItJ9Ccs31htmA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
